create table public."user"
(
    user_id       bigint generated by default as identity
        constraint user_id
            primary key,
    user_email    varchar(255) not null,
    user_login    varchar(255) not null,
    user_name     varchar(255),
    user_birthday date         not null
);

create table public.genre
(
    genre_id   integer generated always as identity
        constraint genre_id
            primary key,
    genre_name varchar(255) not null
);

create table public.mpa_rate
(
    mpa_rate_id          integer generated always as identity
        constraint mpa_rate_id
            primary key,
    mpa_rate_name        varchar(5)   not null,
    mpa_rate_description varchar(255) not null
);

create table public.film
(
    film_id           bigint generated by default as identity
        constraint film_id
            primary key,
    film_name         varchar(255) not null,
    film_description  varchar(200),
    film_release_date date         not null,
    film_duration     integer      not null,
    film_mpa_rate     integer
        constraint film_mpa_rate
            references public.mpa_rate
);

create table public.film_genre
(
    film_id  bigint  not null
        references public.film,
    genre_id integer not null
        references public.genre,
    primary key (film_id, genre_id)
);

create table public.user_friend
(
    user_id   bigint not null
        references public."user",
    friend_id bigint not null
        references public."user",
    primary key (user_id, friend_id)
);

create table public.film_like
(
    film_id bigint not null
        references public.film,
    user_id bigint not null
        references public."user",
    primary key (film_id, user_id)
);
